# Generated by Django 4.1.7 on 2023-05-22 11:21

import collageRegistrar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcer', models.CharField(max_length=50)),
                ('announcement', models.ImageField(upload_to=collageRegistrar.models.Announcement.uploadAnnouncement)),
                ('announcement_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('mothers_fullName', models.CharField(max_length=100)),
                ('address_region', models.CharField(max_length=100)),
                ('address_zone', models.CharField(max_length=100)),
                ('address_woreda', models.CharField(max_length=100)),
                ('address_kebele', models.CharField(max_length=100)),
                ('adress_city', models.CharField(max_length=100)),
                ('address_houseNo', models.CharField(max_length=100)),
                ('address_POBox', models.CharField(max_length=100)),
                ('prep_school_name', models.CharField(max_length=100)),
                ('prep_complete_date', models.DateField()),
                ('prep_school_region', models.CharField(max_length=100)),
                ('prep_school_zone', models.CharField(max_length=100)),
                ('prep_school_woreda', models.CharField(max_length=100)),
                ('prep_school_kebele', models.CharField(max_length=100)),
                ('prep_school_city', models.CharField(max_length=100)),
                ('collage_join_year', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('date_of_withdrawal', models.DateField(null=True)),
                ('demanded_service', models.CharField(max_length=100)),
                ('demand_type', models.CharField(max_length=100)),
                ('estimated_cost', models.CharField(max_length=100)),
                ('date_of_advance_payment', models.DateField(null=True)),
            ],
        ),
    ]
