# Generated by Django 4.1.7 on 2023-05-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collageRegistrar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregitration',
            name='email',
        ),
    ]
