# Generated by Django 4.1.7 on 2023-04-27 03:19

import collageRegistrar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageRegistrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.ImageField(upload_to=collageRegistrar.models.Announcement.uploadAnnouncement),
        ),
    ]
