# Generated by Django 4.1.7 on 2023-05-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collageRegistrar', '0003_courseregitration_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregitration',
            old_name='demand_Service_cash',
            new_name='demand_Service_cashkind',
        ),
        migrations.RemoveField(
            model_name='courseregitration',
            name='demanded_service_kind',
        ),
    ]
