# Generated by Django 4.1.7 on 2023-05-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('dept', models.CharField(default='', max_length=100)),
                ('batch', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
