# Generated by Django 4.1.7 on 2023-03-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roll',
            fields=[
                ('roll', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
    ]
