# Generated by Django 4.1.7 on 2023-03-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='instructor_course',
            field=models.ForeignKey(default='Introductio to Arteficial Intelegence', on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
        ),
        migrations.AddField(
            model_name='users',
            name='roll',
            field=models.ForeignKey(default='Student', on_delete=django.db.models.deletion.CASCADE, to='dashboard.roll'),
        ),
        migrations.AddField(
            model_name='users',
            name='student_department',
            field=models.ForeignKey(default='Computer Science', on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
        ),
    ]
