# Generated by Django 4.1.7 on 2023-03-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.roll'),
        ),
    ]
