# Generated by Django 4.1.7 on 2023-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_users_instructor_course_users_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.CharField(max_length=255),
        ),
    ]
