# Generated by Django 4.1.7 on 2023-03-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_users_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='student_id',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='roll',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='dashboard.roll'),
        ),
        migrations.CreateModel(
            name='courseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('material', models.FileField(upload_to='Materials/<django.db.models.fields.related.ForeignKey>')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
            ],
        ),
    ]
