# Generated by Django 4.1.7 on 2023-03-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_coursematerial_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
        ),
    ]
