# Generated by Django 4.1.7 on 2023-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_users_student_id_alter_users_roll_coursematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material',
            field=models.FileField(upload_to='Materials'),
        ),
    ]
