# Generated by Django 4.1.7 on 2023-03-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_coursematerial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material',
            field=models.FileField(upload_to='Materials\\<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
