# Generated by Django 4.1.7 on 2023-05-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_coursematerial_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('announcement_id', models.CharField(max_length=50)),
            ],
        ),
    ]
