# Generated by Django 4.1.7 on 2023-03-19 08:48

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_coursematerial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material',
            field=models.FileField(upload_to=dashboard.models.upload_filepath),
        ),
    ]
