# Generated by Django 4.1.7 on 2023-03-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_coursematerial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material',
            field=models.FileField(upload_to='Material/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'),
        ),
    ]
