# Generated by Django 4.1.7 on 2023-05-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roll',
            field=models.ForeignKey(default='.', on_delete=django.db.models.deletion.CASCADE, to='dashboard.roll'),
        ),
    ]
