# Generated by Django 4.1.7 on 2023-03-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_coursematerial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='chapter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material',
            field=models.FileField(max_length=255, upload_to='Material/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
