# Generated by Django 4.1.7 on 2023-05-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_users_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='student_department',
            field=models.ForeignKey(default='.', on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
        ),
    ]
