# Generated by Django 4.1.7 on 2023-05-27 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_users_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedannouncements',
            old_name='announcement_id',
            new_name='announcement',
        ),
        migrations.AddField(
            model_name='savedannouncements',
            name='announcer',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
