# Generated by Django 4.1.7 on 2023-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_announcement_id_savedannouncements_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semister',
            field=models.CharField(default='I', max_length=12),
        ),
    ]
